import React from "react";

export const colors = {
    bg: "#181825",
    surface: "#1e1e2e",
    surfaceLight: "#232336",
    border: "#313244",
    borderLight: "#45475a",
    primary: "#cba6f7",
    primaryDim: "#cba6f740",
    text: "#cdd6f4",
    textDim: "#6c7086",
    textMuted: "#585b70",
    success: "#a6e3a1",
    successBg: "#a6e3a120",
    error: "#f38ba8",
    errorBg: "#f38ba820",
    warning: "#fab387",
    warningBg: "#fab38720",
    info: "#89b4fa",
    infoBg: "#89b4fa20",
};

export const commonStyles: Record<string, React.CSSProperties> = {
    page: {
        minHeight: "100vh",
        backgroundColor: colors.bg,
        color: colors.text,
    },
    container: {
        maxWidth: "1200px",
        margin: "0 auto",
        padding: "24px",
    },
    card: {
        backgroundColor: colors.surface,
        borderRadius: "12px",
        border: `1px solid ${colors.border}`,
        padding: "24px",
    },
    btn: {
        padding: "10px 20px",
        backgroundColor: colors.primary,
        color: colors.bg,
        border: "none",
        borderRadius: "8px",
        fontWeight: "bold",
        fontSize: "13px",
        cursor: "pointer",
    },
    btnOutline: {
        padding: "10px 20px",
        backgroundColor: "transparent",
        color: colors.primary,
        border: `1px solid ${colors.primary}`,
        borderRadius: "8px",
        fontWeight: "bold",
        fontSize: "13px",
        cursor: "pointer",
    },
    btnDanger: {
        padding: "10px 20px",
        backgroundColor: colors.error,
        color: colors.bg,
        border: "none",
        borderRadius: "8px",
        fontWeight: "bold",
        fontSize: "13px",
        cursor: "pointer",
    },
    btnSmall: {
        padding: "6px 14px",
        fontSize: "12px",
        borderRadius: "6px",
        border: "none",
        fontWeight: "bold",
        cursor: "pointer",
    },
    input: {
        width: "100%",
        padding: "10px 14px",
        backgroundColor: colors.surfaceLight,
        border: `1px solid ${colors.border}`,
        borderRadius: "8px",
        color: colors.text,
        fontSize: "14px",
        outline: "none",
        boxSizing: "border-box" as const,
    },
    label: {
        display: "block",
        marginBottom: "6px",
        color: colors.textDim,
        fontSize: "13px",
        fontWeight: 500,
    },
    badge: {
        display: "inline-block",
        padding: "3px 10px",
        borderRadius: "12px",
        fontSize: "11px",
        fontWeight: "bold",
    },
    table: {
        width: "100%",
        borderCollapse: "collapse" as const,
    },
    th: {
        textAlign: "left" as const,
        padding: "12px 16px",
        borderBottom: `1px solid ${colors.border}`,
        color: colors.textDim,
        fontSize: "12px",
        fontWeight: 600,
        textTransform: "uppercase" as const,
        letterSpacing: "0.5px",
    },
    td: {
        padding: "14px 16px",
        borderBottom: `1px solid ${colors.border}`,
        fontSize: "14px",
        color: colors.text,
    },
};